-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 16:02:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Salinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Salinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Salinha` ;
USE `Salinha` ;

-- -----------------------------------------------------
-- Table `Salinha`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salinha`.`Produto` (
  `id_produto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `unidade_medida` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `Id_produto_UNIQUE` (`id_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salinha`.`Historico_Movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salinha`.`Historico_Movimentacao` (
  `id_historico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_produto` INT UNSIGNED NOT NULL,
  `tipo_movimentacao` ENUM('entrada', 'saida') NOT NULL,
  `quantidade_movida` INT UNSIGNED NOT NULL,
  `data` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `responsavel` VARCHAR(20) NULL,
  PRIMARY KEY (`id_historico`, `id_produto`),
  UNIQUE INDEX `id_historico_UNIQUE` (`id_historico` ASC) VISIBLE,
  INDEX `fk_HistoricoMovimentacao_Produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_HistoricoMovimentacao_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `Salinha`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salinha`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salinha`.`Estoque` (
  `id_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `data_atualizacao` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_Estoque_Produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `Salinha`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
